### ISSUE TITLE
tokensignin process not creating user

### ISSUE THREAD

**Issue by baberlevi** [KrashLeviathan/L2_speech_ratings#1]
I am putting in the validation code and successfully authenticating to google via Oauth2, but the tokensignin process is not creating a user in the user table.  I haven't had a chance yet to debug to find out why.

Subsequent calls to _includes/checkSession.php then fail to populate the user array, and other functions seem to not work.

**Comment by KrashLeviathan** [comment]
Addressed in f9046331c087cb20d977bd317d947a2e9f5e9705
